---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:4:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 9:16:21【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: connect ETIMEDOUT 47.104.102.223:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2018-4-2 17:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\item\MyModule\company_item_4\node_modules\_pg@4.5.7@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
